### ISSUE TITLE
things to do before automerge

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#785]
To-Dos

- [x] pip check migrator (#771)
- [ ] add pip check to conda build (https://github.com/conda/conda-build/issues/3871)
- [x] make sure sha256 has actually changed before sending PRs (#500, #529)
- [x] make sure the rerender has actually worked before sending PRs
- [ ] implement to big to fail for automerge (#783) 

Future stuff

- [ ] automated bumping of deps w/ depfinder (#22, other issues)

cc @isuruf @CJ-Wright
